### Get all cats
GET http://127.0.0.1:3000/api/v1/cats

### Get cat by ID
GET http://127.0.0.1:3000/api/v1/cats/44

### Get cats by user ID
GET http://127.0.0.1:3000/api/v1/cats/user/37

### Add cat //this no longer works in newer API changes
POST http://127.0.0.1:3000/api/v1/cats
Content-Type: application/json

{
  "cat_name": "Puff",
  "weight": 5,
  "owner": 3552,
  "filename": "puff.jpg",
  "birthdate": "2023-12-12"
}

### Update cat
PUT http://127.0.0.1:3000/api/v1/cats/44
Content-Type: application/json

{
  "weight": 5
}

### Delete cat
DELETE  http://127.0.0.1:3000/api/v1/cats/46

### Get all users
GET http://127.0.0.1:3000/api/v1/users

### Get user by ID
GET http://127.0.0.1:3000/api/v1/users/38

### Add user
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "name": "John Pork",
  "username": "johnpork",
  "email": "jp@metropolia.fi",
  "role": "staff",
  "password": "passingtheword"
}

### Update user
PUT http://127.0.0.1:3000/api/v1/users/38
Content-Type: application/json

{
  "email": "j.p@metropolia.fi"
}

### Delete user
DELETE  http://127.0.0.1:3000/api/v1/users/38